### PR TITLE
Update Params.java

### PR DESCRIPTION
**Pull request by deamn**
TYPE_RAIN="Rain" doesn't work. Use "sum_rain" instead.

### CODE REVIEW

**Comment by lost-carrier** [comment]
Thanks for you contribution...

I've taken "Rain" from here: https://github.com/Netatmo/Netatmo-API-Android/blob/8c93cea9628ac001fcd4fcbc37c47867b2442852/app/src/main/java/weatherstation/netatmo/com/netatmo_api_android/api/model/Params.java#L36

I've checked in more detail. With SCALE_MAX I get values for "Rain", but for "sum_rain" I get ```{"error":{"code":21,"message":"Filter sum_rain does not exists"}}```.

When using some other Scale, I get values for "sum_rain", too, but different ones than "Rain".

"sum_rain_1" and "sum_rain_24" appear not to work in any Scale, despite being on that official SDK.

Any clue? Where did you get that "sum_rain" from?

**Comment by romainlouvet** [comment]
I found "Rain" in https://cbornet.github.io/netatmo-swagger-decl/#operation/getmeasure

**Comment by spooky1310** [comment]
"sum_rain_1" and "sum_rain_24" doesn't work at all for me. 
I would need the sum of rain for 1 day. Setting type to "sum_rain" and the scale to "1day" retrieves the values from the REST API but it cannot be parsed as the type "sum_rain" is missing.

**Comment by lost-carrier** [comment]
Guys, I think I figured something out. Can you please check latest commit on master: https://github.com/lost-carrier/netatmo-api/commit/4c56e8cfcb676fc6db28f8726c13bc27c668276b

...makes sense? ...does 0.6.0-SNAPSHOT work for you?

**Comment by lost-carrier** [comment]
Thanks for confirming @spooky1310 - Release 0.6.0 is on it's way to maven central...

I will close this PR now - still thanks for pointing this out @deamn & @romainlouvet!

**Pull request closed without merging**
