### PR TITLE
Update dependencies, plugins and Maven wrapper

### PR DESCRIPTION
**Pull request by crea-doo**
- Split up build from deploy and added deploy scripts
- Updated dependency and plugin versions
- Clean up

### CODE REVIEW

**Review by lost-carrier — CHANGES_REQUESTED** [review]
Cool! Thanks for your contribution - once again ;-). Looks fine to me, but could you drop that slf4j stuff? It's not really used in this project...

**Comment by crea-doo** [comment]
I removed the explicit dependency to slf4j though it's still a transitive dependency of Apache Oltu. Thought it was used in the unit tests - but I missed that the interaction is only mocked.

**Review by lost-carrier — APPROVED** [review]
Awesome - thanks!

**Comment by lost-carrier** [comment]
Hmm... can you give me some hint? I've tried your deploy.sh for publishing it to OSSRH. Worked fine so far - thanks for that. v0.4.1 should be available shortly...

I noticed that "-Prelease" parameter and thought it might somehow automatically trigger that "Release" button when that thingy is successfully "closed" in Nexus. However: I still had to press "Release" manually. So is this  "-Prelease" meant for something else...?

It's just that I really dislike this Nexus Web-UI so it would be handy to have it triggered automatically... ;-)

**Comment by crea-doo** [comment]
The "-Prelease" just activates the Maven profile (see https://github.com/lost-carrier/netatmo-api/blob/8a62eed9c74200b44e06455156492288141b483b/pom.xml#L210)
If you want to automatically release and close the process on the Nexus-Web-UI that should work with setting the param "autoReleaseAfterClose" to "true" (see https://github.com/lost-carrier/netatmo-api/blob/8a62eed9c74200b44e06455156492288141b483b/pom.xml#L242)

**Comment by lost-carrier** [comment]
I think it worked... awesome - thanks!

**Pull request merged**
